title: Sarah Grego # your name (or website title) here
logo: "/images/IMG_0380.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  7+ years of Geographic Information Systems
  with experience in database development,
  spatial analysis, & Python. Possess Bachelor's
  Degree in GIS from Louisisna State University
  & pursuing a Master's Degree in 
  Geospatial Technology. CEO of GEOgrego.
  <br><br>
  Currently, I am the GIS Data Analyst at Lynn-Levy Land Co.
  in Baton Rouge, LA. Working closely with the contractors, developers, utilities companies, planning departments
  and local government policies.
  <br><br>
  <a href="https://www.linkedin.com/in/sarahgrego/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://twitter.com/GEOSarahGrego">View My Twitter Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
