title: Sarah Grego # your name (or website title) here
logo: "/images/IMG_0380.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  6+ years of Geographic Information Systems
  with experience in database development,
  spatial analysis, & Python. Possess Bachelor's
  Degree in GIS from Louisisna State University
  & pursuing a Master's Degree in 
  Geospatial Technology.
  <br><br>
  Currently I am the GIS Developer at the City of San Angelo
  in West Texas. Working closely with the Planning Department
  and local government policies.
  <br><br>
  <a href="https://www.linkedin.com/in/sarahgrego/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
